name: Build GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Create production env file
        run: |
          touch .env
          echo BASE_PATH=${{ vars.BASE_PATH }} >> .env
          echo NEXT_PUBLIC_GTM_ID=${{ secrets.NEXT_PUBLIC_GTM_ID }} >> .env

      - name: Install and Build 🔧
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: |
          yarn
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean: true
